### ISSUE TITLE
Descriptions support

### ISSUE THREAD

**Issue by agnewp** [mununki/gqlmerge#23]
i seem to throw exceptions from your lexer when i attempt to add any kind of self documentation for my schema.  

do you support this feature: https://graphql.github.io/graphql-spec/June2018/#sec-Descriptions

**Comment by mununki** [comment]
Thank you for raising an issue for a new feature. I'll add it.

**Comment by hulucc** [comment]
when ???

**Comment by mununki** [comment]
Sorry for the huge delay. I've been away from this project and Go for a while. I finally fix this issue not to panic due to descriptions. But still, it doesn't parse the descriptions and write them down into merged schema. I think it is quite bigger task than I thought initially, regarding #30 #31 

https://github.com/mattdamon108/gqlmerge/releases/tag/v0.2.5

**Comment by mununki** [comment]
Sorry for the huge delay, I've released a fixed version that doesn't strip descriptions and comments. Can you test with https://github.com/mununki/gqlmerge/releases/tag/v0.2.9?
